version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: install exiftool
          command: sudo apt update && sudo apt install -y exiftool
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - run:
          name: test samples
          command: npm run test-samples
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./exif-samples
            - ./metadata-extractor-images
